title: ""
theme: jekyll-theme-minimal
logo: Screenshot from 2020-11-14 23-30-34.png
description: "<html>VentureGear is a mobile application designed for adventurous people to find new sports, new gyms and to rent equipments.<br><br>

<b>1. Find new ways to practice sports</b><br>
We offer a fully interactive map that helps you find the sports that you can practice near you or at a custom location<br><br>

<b>2. Help your business grow</b><br>
VentureGear offers an innovative way to advertise your business to the public<br><br>

<b>3. Stay healthy</b><br>
By offering more solutions to sports enthusiasts, we hope to help both the sports enthusiasts and newcomers into new sports<br><br><br><br><br><br><br><br>

</html>"
